namespace: t_systems_mms
name: letsencrypt
version: 0.0.8
readme: README.md
authors:
  - Sebastian Gumprich <sebastian.gumprich@t-systems.com>
  - Andreas Hering <andreas.hering@t-systems.com>
description: >-
  This collection contains a role for issuing ssl certificates from Let's
  Encrypt via dns- or http-challenge
license:
  - GPL-2.0-or-later
license_file: ''
tags:
  - letsencrypt
  - security
  - certificates
dependencies:
  community.crypto: '>=1.0.0'
  openstack.cloud: '>=1.2.1'
repository: 'https://github.com/T-Systems-MMS/ansible-collection-letsencrypt'
documentation: 'https://github.com/T-Systems-MMS/ansible-collection-letsencrypt'
homepage: 'https://github.com/T-Systems-MMS/ansible-collection-letsencrypt'
issues: 'https://github.com/T-Systems-MMS/ansible-collection-letsencrypt/issues'
build_ignore:
  - .ansible-lint
  - .gitattributes
  - .github
  - .yamllint.cfg
  - tests
