---
- name: Create key to be used for acme account
  community.crypto.openssl_privatekey:
    path: "{{ acme_account_key_path }}"
    size: "{{ acme_account_key_size }}"
    type: "{{ acme_account_key_type }}"
    curve: "{{ acme_account_key_curve }}"
  when:
    - acme_account_key_content is not defined
  no_log: true

- name: Create account key file from acme_account_key_content-variable # noqa template-instead-of-copy
  ansible.builtin.copy:
    dest: "{{ acme_account_key_path }}"
    content: "{{ acme_account_key_content }}"
    mode: "0400"
  when:
    - acme_account_key_content is defined
  no_log: true

- name: Create key to be used for certificate
  community.crypto.openssl_privatekey:
    path: "{{ acme_private_key_path }}"
    size: "{{ acme_private_key_size }}"
    type: "{{ acme_private_key_type }}"
    curve: "{{ acme_private_key_curve }}"
  when:
    - acme_private_key_content is not defined
  no_log: true

- name: Create private key file from acme_private_key_content-variable # noqa template-instead-of-copy
  ansible.builtin.copy:
    dest: "{{ acme_private_key_path }}"
    content: "{{ acme_private_key_content }}"
    mode: "0400"
  when:
    - acme_private_key_content is defined
  no_log: true
