---
- name: install prerequisites on localhost
  delegate_to: localhost
  package:
    name:
      - python-boto3
    state: present
    use: "{{ acme_letsencrypt_prerequisites_packagemanager }}"

- name: validate challenge only if it is created or changed
  when: challenge is changed
  block:
    - name: create challenge file with SAN domain for s3 upload
      copy:
        dest: "acme-challenge.{{ item }}"
        content: "{{ challenge['challenge_data'][item]['http-01']['resource_value'] }}"
        mode: 0640
      loop: "{{ acme_letsencrypt_domain.subject_alt_name }}"
      when:
        - acme_letsencrypt_domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined

    - name: upload challenge file for SAN domain to s3 bucket
      aws_s3:
        aws_access_key: "{{ letsencrypt_s3_access_key }}"
        aws_secret_key: "{{ letsencrypt_s3_secret_key }}"
        bucket: "{{ letsencrypt_s3_bucket_name }}"
        object: "{{ challenge['challenge_data'][item]['http-01']['resource'] }}"
        src: "acme-challenge.{{ item }}"
        mode: "put"
        region: "{{ acme_letsencrypt_s3_config_region }}"
        permission: "public-read"
      loop: "{{ acme_letsencrypt_domain.subject_alt_name }}"
      when:
        - acme_letsencrypt_domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined

    # validate certficate
    - name: Let the challenge be validated and retrieve the cert and intermediate certificate
      acme_certificate:
        account_key_src: "{{ acme_letsencrypt_account_key_path }}"
        account_email: "{{ acme_letsencrypt_account_email }}"
        csr: "{{ acme_letsencrypt_csr_path }}"
        cert: "{{ acme_letsencrypt_cert_path }}"
        fullchain: "{{ acme_letsencrypt_fullchain_path }}"
        chain: "{{ acme_letsencrypt_intermediate_path }}"
        challenge: http-01
        force: "{{ acme_letsencrypt_force_renewal | default(false) }}"
        acme_directory: "{{ acme_letsencrypt_directory }}"
        acme_version: 2
        terms_agreed: true
        remaining_days: "{{ acme_letsencrypt_remaining_days }}"
        data: "{{ challenge }}"

    - name: remove challenge file for SAN domain from s3 bucket
      aws_s3:
        aws_access_key: "{{ letsencrypt_s3_access_key }}"
        aws_secret_key: "{{ letsencrypt_s3_secret_key }}"
        bucket: "{{ letsencrypt_s3_bucket_name }}"
        object: "{{ challenge['challenge_data'][item]['http-01']['resource'] }}"
        mode: "delobj"
        region: "{{ acme_letsencrypt_s3_config_region }}"
      loop: "{{ acme_letsencrypt_domain.subject_alt_name }}"
      when:
        - acme_letsencrypt_domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined

    - name: remove challenge file for SAN domain from fs
      file:
        dest: "acme-challenge.{{ item }}"
        state: absent
      loop: "{{ acme_letsencrypt_domain.subject_alt_name }}"
      when:
        - acme_letsencrypt_domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined
