---
### include/role 3 - validate challenge
- name: validate challenge only if it is created or changed
  when: challenge is changed
  block:
    - name: Login to autodns
      uri:
        url: "https://api.autodns.com/v1/login"
        method: POST
        body_format: json
        body:
          { "context": "4",
            "user": "{{ acme_letsencrypt_dns_user }}",
            "password": "{{ acme_letsencrypt_dns_password }}"
          }
      register: login

    - name: add a new TXT record to the SAN domains
      uri:
        url: "https://api.autodns.com/v1/zone/{{ acme_letsencrypt_domain.zone }}/a.ns14.net"
        method: PATCH
        body_format: json
        body:
          {
            "origin": "{{ item }}",
            "resourceRecordsAdd": [
              {
                # "remove" '*.' from entry when it occurs. without it it would try to create a
                # record like _acme-challenge.*.example.com which is not allowed by AutoDNS
                # see: https://jinja.palletsprojects.com/en/master/templates/#replace
                # and: https://jbmoelker.github.io/jinja-compat-tests/filters/replace/#pattern
                "name": "_acme-challenge.{{ item | replace ('*.','') }}",
                "ttl": 60,
                "type": "TXT",
                "value": "{{ challenge['challenge_data'][item]['dns-01']['resource_value'] }}"
              }
            ]
          }
        headers:
          Cookie: "{{ login.set_cookie }}"
      loop: "{{ acme_letsencrypt_domain.subject_alt_name }}"
      when:
        - acme_letsencrypt_domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined

    - name: Let the challenge be validated and retrieve the cert and intermediate certificate
      acme_letsencrypt_certificate:
        account_key_src: "{{ acme_letsencrypt_account_key_path }}"
        account_email: "{{ acme_letsencrypt_account_email }}"
        csr: "{{ acme_letsencrypt_csr_path }}"
        cert: "{{ acme_letsencrypt_cert_path }}"
        fullchain: "{{ acme_letsencrypt_fullchain_path }}"
        chain: "{{ acme_letsencrypt_intermediate_path }}"
        challenge: dns-01
        force: "{{ acme_letsencrypt_force_renewal | default(false) }}"
        acme_directory: "{{ acme_letsencrypt_directory }}"
        acme_version: 2
        terms_agreed: true
        remaining_days: "{{ acme_letsencrypt_remaining_days }}"
        data: "{{ challenge }}"

    - name: remove created SAN TXT records to keep DNS zone clean
      uri:
        url: "https://api.autodns.com/v1/zone/{{ acme_letsencrypt_domain.zone }}/a.ns14.net"
        method: PATCH
        body_format: json
        body:
          {
            "origin": "{{ item }}",
            "resourceRecordsRem": [
              {
                "name": "_acme-challenge.{{ item | replace ('*.','') }}",
                "ttl": 60,
                "type": "TXT",
                "value": "{{ challenge['challenge_data'][item]['dns-01']['resource_value'] }}"
              }
            ]
          }
        headers:
          Cookie: "{{ login.set_cookie }}"
      loop: "{{ acme_letsencrypt_domain.subject_alt_name }}"
      when:
        - acme_letsencrypt_domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined
