- name: create the certificate for example.com
  hosts: localhost
  roles:
    - letsencrypt
  vars:
    domain:
      certificate_name: "example.com"
      zone: "example.com"
      email_address: "ssl-admin@example.com"
      subject_alt_name:
        - example.com
        - domain1.example.com
        - domain2.example.com
    letsencrypt_do_http_challenge: true
    letsencrypt_do_dns_challenge: false
    letsencrypt_use_acme_live_directory: false
    account_email: "ssl-admin@example.com"
    private_key_content: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ....
    letsencrypt_s3_bucket_name: "example-ssl-bucket"
    letsencrypt_s3_access_key: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              ...
    letsencrypt_s3_secret_key: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              ...

# Azure DNS
- name: create the certificate for example.com
  hosts: localhost
  roles:
    - letsencrypt
  vars:
    letsencrypt_create_private_keys: true
    letsencrypt_do_http_challenge: false
    letsencrypt_do_dns_challenge: true
    letsencrypt_dns_provider: azure
    letsencrypt_use_acme_live_directory: true
    account_email: "ssl-admin@example.com"
    azure_resource_group: "azure_resource_group"
    convert_cert_to: pfx
    domain:
      certificate_name: "example.com"
      zone: "example.com"
      email_address: "ssl-admin@example.com"
      subject_alt_name:
        top_level:
          - example.com
          - domain1.example.com
          - domain2.example.com
        second_level:
          - domain1.example.co.uk"
