---
- name: Create CSR for certificate
  openssl_csr:
    path: "{{ acme_csr_path }}"
    privatekey_path: "{{ acme_private_key_path }}"
    acme_email_address: "{{ domain.acme_email_address }}"
    acme_subject_alt_name: "DNS:{{ domain.acme_subject_alt_name | join(',DNS:') }}"
  when:
    - domain.acme_subject_alt_name.top_level is undefined and domain.acme_subject_alt_name.second_level is undefined
    - '"dns-01" in acme_provider_path'

- name: Create CSR for certificate
  openssl_csr:
    path: "{{ acme_csr_path }}"
    privatekey_path: "{{ acme_private_key_path }}"
    acme_email_address: "{{ domain.acme_email_address }}"
    acme_subject_alt_name: "DNS:{{ (domain.acme_subject_alt_name.top_level | default([])) | union(domain.acme_subject_alt_name.second_level | default([])) | join(',DNS:') }}"
  when:
    - domain.acme_subject_alt_name.top_level is defined or domain.acme_subject_alt_name.second_level is defined
    - '"dns-01" in acme_provider_path'

- name: Create CSR for certificate
  openssl_csr:
    path: "{{ acme_csr_path }}"
    privatekey_path: "{{ acme_private_key_path }}"
    acme_email_address: "{{ domain.acme_email_address }}"
    acme_subject_alt_name: "DNS:{{ domain.acme_subject_alt_name | join(',DNS:') }}"
  when:
    - '"http-01" in acme_provider_path'
