---
- name: set fact for acme_directory
  set_fact:
    acme_directory: "{{ acme_staging_directory }}"
  when:
    - not letsencrypt_use_acme_live_directory

- name: set fact for acme_directory
  set_fact:
    acme_directory: "{{ acme_live_directory }}"
  when:
    - letsencrypt_use_acme_live_directory | bool

- name: create directories for letsencrypt
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ letsencrypt_conf_dir }}"
    - "{{ letsencrypt_cert_dir }}"

- name: set fact for letsencrypt_conf_dir_group
  set_fact:
    letsencrypt_conf_dir_group: "{{ letsencrypt_conf_dir_user }}"
  when: letsencrypt_conf_dir_group | length == 0
