---
- name: preconditions
  include_tasks: preconditions.yml

- name: run certificate generation
  include_tasks: create-keys.yml

- name: do http challenge
  include_tasks: http-challenge.yml
  when:
    - letsencrypt_http_provider is defined

- name: do dns challenge
  include_tasks: dns-challenge.yml
  when:
    - letsencrypt_dns_provider is defined

- name: convert certificate
  include_tasks: convert_certificate.yml
  when:
    - convert_cert_to is defined
