---
- name: check if a challenge provider is used
  assert:
    that:
      - letsencrypt_dns_provider is defined or letsencrypt_http_provider is defined
    fail_msg: "You need to set a 'letsencrypt_dns_provider' or 'letsencrypt_http_provider'."

- name: set fact for acme_directory depending on what is set in letsencrypt_use_acme_live_directory
  set_fact:
    acme_directory: "{{ letsencrypt_use_acme_live_directory | ternary(acme_live_directory, acme_staging_directory) }}"

- name: create directories for letsencrypt
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ letsencrypt_conf_dir }}"
    - "{{ letsencrypt_cert_dir }}"
