---
- name: check if a challenge provider is used
  assert:
    that:
      - acme_do_dns_challenge | bool or acme_do_http_challenge | bool
    fail_msg: "You need to set acme_do_dns_challenge'' or 'acme_do_http_challenge'."

- name: check if a DNS challenge provider is used
  assert:
    that:
      - acme_challenge_provider is defined
    fail_msg: "You need to set a DNS challenge provider ('acme_challenge_provider') if you use the DNS challenge."
  when:
    - acme_do_dns_challenge | bool

- name: check if a HTTP challenge provider is used
  assert:
    that:
      - acme_challenge_provider is defined
    fail_msg: "You need to set a HTTP challenge provider ('acme_challenge_provider') if you use the HTTP challenge."
  when:
    - acme_do_http_challenge | bool

- name: set fact for acme_directory depending on what is set in acme_use_live_directory
  set_fact:
    acme_directory: "{{ acme_use_live_directory | ternary(acme_live_directory, acme_staging_directory) }}"

- name: create directories for letsencrypt
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
    - "{{ acme_conf_dir }}"
    - "{{ acme_cert_dir }}"
