---
### include/role 3 - validate challenge
- name: validate challenge only if it is created or changed
  when: challenge is changed
  block:
    - name: add a new TXT record to the SAN domains
      uri:
        url: "https://dns.hetzner.com/api/v1/records"
        method: POST
        body_format: json
        body:
          {
            "name": "_acme-challenge",
            "ttl": 60,
            "type": "TXT",
            "value": "{{ challenge['challenge_data'][item]['dns-01']['resource_value'] }}",
            "zone_id": "{{ domain.zone }}",
          }
        headers:
          Auth-API-Token: "{{ dns_auth_token }}"
      loop: "{{ domain.subject_alt_name }}"
      register: records
      when:
        - domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - challenge['challenge_data'][item] is defined

    - name: Wait 20 seconds
      pause:
        seconds: 20

    - name: Let the challenge be validated and retrieve the cert and intermediate certificate
      acme_certificate:
        account_key_src: "{{ account_key_path }}"
        account_email: "{{ account_email }}"
        csr: "{{ csr_path }}"
        cert: "{{ cert_path }}"
        fullchain: "{{ fullchain_path }}"
        chain: "{{ intermediate_path }}"
        challenge: dns-01
        force: "{{ force_renewal | default(false) }}"
        acme_directory: "{{ acme_directory }}"
        acme_version: 2
        terms_agreed: true
        remaining_days: "{{ remaining_days }}"
        data: "{{ challenge }}"

    - name: remove created SAN TXT records to keep DNS zone clean
      uri:
        url: "https://dns.hetzner.com/api/v1/records/{{ item }}"
        method: DELETE
        headers:
          Auth-API-Token: "{{ dns_auth_token }}"
      loop: "{{ records | json_query('results[*].json.record.id') }}"
      when:
        - domain.subject_alt_name is defined
        # only runs if the challenge is run the first time, because then there is challenge_data
        - item is defined
